### ISSUE TITLE
Button to book a lecture inside the cell of the calender 

### ISSUE THREAD

**Issue by CalogeroPisano** [se2team3/PULSeBS#21]
####  Giovanni: first year BSc student
I would like to have a button inside the calendar cell of the lecture to book a seat with that instead of open a modal.
Good job.

**Comment by bit97** [comment]
The button feature has not been implemented, but with 598ccd1 merge we have improved the UI by showing a different cursor when hovering the lecture

![cursor](https://user-images.githubusercontent.com/56674946/100545780-d877a880-325d-11eb-809e-d9aa91132dab.gif)
