### ISSUE TITLE
Strange behaviours on Course filters

### ISSUE THREAD

**Issue by bit97** [se2team3/PULSeBS#40]
Canceled/Booked filters work fine, but the list of Courses of the actual view seem to not work properly
1. when a) you have only one course in week b) uncheck the badge c) change week and come back to original week -> the badge is checked but the calendar does not render the lectures
2. when trying to play around with filtering multiple lectures
3. ... more? (*hopefully not*)

![1](https://user-images.githubusercontent.com/56674946/100938074-5359f100-34f4-11eb-9e34-1080788d07e4.gif)
![2](https://user-images.githubusercontent.com/56674946/100938042-41784e00-34f4-11eb-8ec2-aa2d57caebe7.gif)

**Comment by lucarinelli** [comment]
The fix for this hit master in the previous days, closing this.
