### ISSUE TITLE
Story 1: User doesn`t directly visit calendar page. 

### ISSUE THREAD

**Issue by GalibAlili** [se2team3/PULSeBS#67]
Execution of test: S1_1, step 2.
https://github.com/se2team3/PULSeBS/blob/master/e2e/execution/Story_1/story1_test1.md

Story 1: User doesn`t directly visit calendar page, in middle of redirecting page after login, app displays "not found"
![Step2_Error](https://user-images.githubusercontent.com/32265268/104516974-8c0ddf80-55f5-11eb-94a0-79509fc317be.png)

**Comment by lucarinelli** [comment]
Fixed in 2.0.0
