### ISSUE TITLE
Story 1: No response when incorrect credentials are entered during login

### ISSUE THREAD

**Issue by GalibAlili** [se2team3/PULSeBS#68]
Execution of test: S1_4, step 2.
https://github.com/se2team3/PULSeBS/blob/master/e2e/execution/Story_1/story1_test1.md

No response when incorrect credentials are entered, page only displays "Not found"

![Step2](https://user-images.githubusercontent.com/32265268/104517288-0b031800-55f6-11eb-9e97-251d61d37b4d.png)

**Comment by lucarinelli** [comment]
Fixed
